apiVersion: v1
kind: Namespace
metadata:
  name: cats
  labels:
    name: cats
---
apiVersion: fine-controller-csharp-example-01.io/v1
kind: V1Cat
metadata:
  name: fluffy
  namespace: cats
spec:
  age1: 5
  name1: Fluffy
---
apiVersion: fine-controller-csharp-example-01.io/v2
kind: V2Cat
metadata:
  name: whiskers
  namespace: cats
spec:
  age2: 3
  name2: Whiskers
---
apiVersion: fine-controller-csharp-example-01.io/v1
kind: V1House
metadata:
  name: blue-house
spec:
  color: blue